In [1]:
import numpy as np

In [4]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a_1 = np.array([[1,2,3],[4,5,6]])
a_1.shape

(2, 3)

In [9]:
a_1[0]

array([1, 2, 3])

In [11]:
a_1[1]

array([4, 5, 6])

In [13]:
a_1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
a_1.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
a_1.ravel()

array([1, 2, 3, 4, 5, 6])

In [35]:
a_1[1]

array([4, 5, 6])

In [34]:
a_1

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
a_1[a_1 > 4]

array([5, 6])

In [64]:
x = np.arange(20)
x = x.reshape(-1,1)
np.random.seed(0)
y = np.random.rand(20)
y = np.where( y < 0.5 , 0, 1).reshape(-1,1)
y

array([[1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1]])

In [66]:
x[:][y == 1]

array([ 0,  1,  2,  3,  5,  7,  8, 10, 11, 12, 13, 17, 18, 19])

In [70]:
array_1 = np.array([[1,2],[3,4],[5,6]])
array_2 = np.array([[7,8],[9,10],[11,12]])

np.vstack([array_1,array_2])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [73]:
np.hstack([array_1,array_2])

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10],
       [ 5,  6, 11, 12]])

In [78]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [123]:
array = np.random.rand(12).reshape(-1,2)
array
array_3 = np.round(array, 2)
array_3.shape


(6, 2)

In [132]:
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()
iris_df = pd.DataFrame(data = iris.data, columns = iris.feature_names)
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [142]:
np.random.seed(10)
df = pd.DataFrame(data = np.random.randn(5,5), index=['A','B','C','D','E'], 
                  columns = ['C1','C2','C3','C4','C5'])
df


C1        C2        C3        C4        C5
A  1.331587  0.715279 -1.545400 -0.008384  0.621336
B -0.720086  0.265512  0.108549  0.004291 -0.174600
C  0.433026  1.203037 -0.965066  1.028274  0.228630
D  0.445138 -1.136602  0.135137  1.484537 -1.079805
E -1.977728 -1.743372  0.266070  2.384967  1.123691

In [145]:
df.loc['A']

C1    1.331587
C2    0.715279
C3   -1.545400
C4   -0.008384
C5    0.621336
Name: A, dtype: float64

In [148]:
df.loc[:,'C3']

A   -1.545400
B    0.108549
C   -0.965066
D    0.135137
E    0.266070
Name: C3, dtype: float64

In [150]:
df.loc['A',['C1','C3']]

C1    1.331587
C3   -1.545400
Name: A, dtype: float64

In [152]:
df > 0

C1     C2     C3     C4     C5
A   True   True  False  False   True
B  False   True   True   True  False
C   True   True  False   True   True
D   True  False   True   True  False
E  False  False   True   True   True

In [154]:
df.where(df > 0)

C1        C2        C3        C4        C5
A  1.331587  0.715279       NaN       NaN  0.621336
B       NaN  0.265512  0.108549  0.004291       NaN
C  0.433026  1.203037       NaN  1.028274  0.228630
D  0.445138       NaN  0.135137  1.484537       NaN
E       NaN       NaN  0.266070  2.384967  1.123691

In [164]:
df[df['C1'] > 0]

C1        C2        C3        C4        C5
A  1.331587  0.715279 -1.545400 -0.008384  0.621336
C  0.433026  1.203037 -0.965066  1.028274  0.228630
D  0.445138 -1.136602  0.135137  1.484537 -1.079805

In [166]:
df['C1']

A    1.331587
B   -0.720086
C    0.433026
D    0.445138
E   -1.977728
Name: C1, dtype: float64

In [167]:
df = pd.DataFrame(data=[[1, 2, 3, np.nan, 4], 
                        [5, np.nan, 6, np.nan, 7],
                        [8, 9, 10, np.nan, 11],
                        [12, np.nan, np.nan, np.nan, 13],
                        [14, 15, 16, 17, 18]],
                  index=['A', 'B', 'C', 'D', 'E'],
                  columns=['C1', 'C2', 'C3', 'C4', 'C5'])
df

C1    C2    C3    C4  C5
A   1   2.0   3.0   NaN   4
B   5   NaN   6.0   NaN   7
C   8   9.0  10.0   NaN  11
D  12   NaN   NaN   NaN  13
E  14  15.0  16.0  17.0  18

In [170]:
df['C2'].dropna()

A     2.0
C     9.0
E    15.0
Name: C2, dtype: float64

In [172]:
df[df['C2'].isnull() == False]

C1    C2    C3    C4  C5
A   1   2.0   3.0   NaN   4
C   8   9.0  10.0   NaN  11
E  14  15.0  16.0  17.0  18