In [2]:
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd

In [8]:
iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [15]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df["target"]=iris.target
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [36]:
x = iris.data[50:,2].reshape(-1,1)
y = iris.target[50:]-1
x
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [37]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [38]:
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)
x_scaled

array([[-0.25077906],
       [-0.49425387],
       [-0.00730424],
       [-1.10294091],
       [-0.37251647],
       [-0.49425387],
       [-0.25077906],
       [-1.95510276],
       [-0.37251647],
       [-1.22467832],
       [-1.71162795],
       [-0.8594661 ],
       [-1.10294091],
       [-0.25077906],
       [-1.58989054],
       [-0.61599128],
       [-0.49425387],
       [-0.9812035 ],
       [-0.49425387],
       [-1.22467832],
       [-0.12904165],
       [-1.10294091],
       [-0.00730424],
       [-0.25077906],
       [-0.73772869],
       [-0.61599128],
       [-0.12904165],
       [ 0.11443316],
       [-0.49425387],
       [-1.71162795],
       [-1.34641572],
       [-1.46815313],
       [-1.22467832],
       [ 0.23617057],
       [-0.49425387],
       [-0.49425387],
       [-0.25077906],
       [-0.61599128],
       [-0.9812035 ],
       [-1.10294091],
       [-0.61599128],
       [-0.37251647],
       [-1.10294091],
       [-1.95510276],
       [-0.8594661 ],
       [-0

In [39]:
x_train,x_test,y_train,y_test = train_test_split(x_scaled,y,random_state = 0)

In [40]:
log_reg = LogisticRegression().fit(x_train,y_train)

/Users/seru/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [41]:
log_reg.intercept_,log_reg.coef_

(array([0.26459322]), array([[3.15196557]]))

In [43]:
print(log_reg.score(x_train,y_train))
print(log_reg.score(x_test,y_test))

0.9466666666666667
0.88


In [47]:
log_reg.(x_train,y_train)

TypeError: 'LogisticRegression' object is not callable